spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
    #    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-wz907xrba87g5e4e75o.mysql.rds.aliyuncs.com:3306/ifund?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Root_123456

# 服务启动访问端口
server:
  port: 6688
